### ISSUE TITLE
[META] Crypto / Security

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1046]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **Cryptography**
- **Security**

- [ ] Berty Protocol https://github.com/berty/berty/issues/1182

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [ ] Create a pinentry library #11
- [ ] Implement paperkey #82
- [ ] Support FIDO U2F #139
- [ ] Add random padding in Event #171
- [ ] Implement perfect forward secrecy #179
- [ ] HMAC-Authenticated Diffie-Hellman (RFC4650) or equivalent #663
- [ ] Implement deniable encryption #181
- [ ] Have `Envelope.Marshal()` and `Envelope.Unmarshal()` methods (#161)

### Enclave
- [ ] Add enclave support for Android #151
- [ ] Add enclave support for Windows #152
- [ ] Add enclave support for Linux #153
- [ ] Add enclave support for BSD #11 154
- [ ] Consider to use NaCl embedded inside an Intel SGX Enclave #347
