### ISSUE TITLE
[META] BLE

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1047]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **Bluetooth Low Energy (BLE)**

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [x] improve(ble): Improve iOS BLE and Yamux logging #905
- [x] feat(ios ble): Implement new Android logic on iOS #904
- [x] feat(android ble): Implement binary search for MTU agreement on Android #900
- [ ] fix(ble): Fix iOS <-> Android BLE handshake #903
- [ ] feat(ble): Design and implement a write timeout strategy (define role of yamux, libp2p and native code) #901
- [ ] feat(ble): Improve interaction between libp2p and BLE native code #902
- [ ] feat(ble): Check BLE compatibility during app init then, if incompatible, disable BLE toggle in app settings #896
- [ ] feat(ble): Check if BLE initialized properly before using it as a transport #897
- [ ] feat(android ble): Convert BLE lib to a react-native module #898
