### ISSUE TITLE
[META] Tooling

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1048]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **Tooling**
- **Devtools**

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [ ] Refactor cobra + add env var support #291
- [ ] Tracing: persist spanid between clients #337
- [ ] Fix: avoid sharing node_modules between host and docker container #375
- [ ] Haptic feedback on state changes #392
- [ ] Add "berty logs" command #611
- [ ] Deeplink to configure default bootstrap #618
- [ ] Persistent node event #658
- [ ] Logs improvements #706
- [ ] Store perf/stats events every N seconds #710
- [ ] Unify logging and tracing #712
- [ ] Display bandwidth info on mobile #723
- [ ] Flush db, but keep identity #767
- [ ] pkg/errorcodes improvements #802
- [ ] Display (debug?) infos in contact & conversation pages #882
- [ ] add a blocking `WaitAck()` helper (#955)

### Jaeger
- [ ] Have a way of seeing unfinished spans #698
- [ ] Add some useful information as tags #699

### Devtools
- [ ] Ping#339
- [ ] Append `account.Infos()` to the current list of infos #535
- [ ] Implement custom bootstrap in network config #587
- [ ] List network subscriptions #596
- [ ] "network speedtest" using libp2p #343
- [ ] "protocol speedtest" using events #342
- [ ] Help developers #644
- [ ] Add an "AddAirtableContacts" button in devtools #956
- [ ] Handle sighup/ctrl+t to display devel informations #958
