### ISSUE TITLE
[META] CI / CD / Deploy / Release / Infra

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1049]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **Continuous Integration (CI)**
- **Continuous Delivery (CD)**
- **Deployments / Releases**
- **Infrastructure**

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [ ] Setup BuildKite for native builds #369
- [ ] Speedup mobile builds #431 
- [ ] New integration test that uses the network stacks #622
- [ ] Reorganize docker-compose files to reuse components #691
- [ ] Publish artifacts on an s3 bucket #795
- [ ] Add a way of specifying build-time configuration to the JS client #692

### CI
- [ ] [design] Secure CI/CD #952
- [ ] Run lint against yaml #97
- [ ] Run lint against protobuf files #98
- [ ] Add CI cronjob that regenerates and publishes docker images #190
- [ ] Checkout gotestsum #476
- [ ] Support coverpkg=berty.tech/core/... on circleci #483
- [ ] go.mod validity should be tested on CI #751
- [ ] Speedup CI by caching "go get" calls #801
- [ ] Implement integration tests agent #937
- [ ] Add integration tests in the CI pipeline #939
- [ ] Bind Cavy hooks and custom library components in a clean way #960
