### ISSUE TITLE
[META] Features / improvements

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1050]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **New features**
- **Improvements**
- **Ideas**

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [ ] Support multi-devices #14
- [ ] Create a network/onion library #18
- [ ] Create directory services #19
- [ ] Create support service #21
- [x] Initial desktop app #27
- [ ] Add feature : mark contact as verified #735
- [ ] Think about a way of having temporary accounts #1010

### UI/UX improvements
- [ ] [UI] Unify colors #562
- [ ] [UI] Display infos under messages #561
- [ ] [UI] Create generic "large blue button" component & use it everywhere #885
- [x] [UI] Add badge for each conversation #1093 
- [x] [UI] Add badge notif on bottom tab menu for new message #1014
- [x] [UI] Add badge notif on bottom tab menu for contact request #1013
- [x] [UI] When scanning for first time, don't display camera permission right away : instead display a button "activate camera" #1106  
- [ ] configure API locales dynamically (#817)

### Improvements
- [ ] Improve delete conversation #806

### Classic chat features
- [x] Implement group conversations #43 
- [ ] Implement multi-destination envelopes (conversation) #178
- [ ] Implement self-destruct messages #84
- [ ] Implement rich messages #85
- [ ] Implement "is typing" feature #293
- [ ] Implement "message read" feature #733
- [ ] Implement wizz/yo like feature #794

### Async messaging
It can be implemented in various ways. Only one could be done to consider it present in the app.
- [ ] Add trusted-contacts based async communication #36 

### VOIP
As we have the VoIP entitlement in the iOS app we are required to have a VoIP functionality in Berty.

### Multiple account on same device
- [ ] Implement sigchain rebase #144
- [ ] https://github.com/berty/berty/issues/303

### Performance optimizations

* [ ] Make Sqlcipher threadsafe (https://github.com/berty/berty/issues/89)
* [ ] Configure SQL indices (#386)

### Ideas

- [ ] use "api_version" to display a message "your contact use a too old version of the app"
- [ ] setup TLS beween client and node API #217 -
