### ISSUE TITLE
[META] Network

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1052]
This is a **meta issue** that regroups all issues & ideas regarding the following topics : 
- **Network**

*Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them*

- [ ] Define interfaces and restructure folder /core/network #1057 
- [ ] Send multiple Event at once per channel #172 
- [ ] Implement a rotating channel ID for conversations #175 -> obsolete
- [ ] Test sending multiple time the same messages, in different orders #197
- [ ] Persistant peerstore #299
- [ ] Setup a timeout for pubsub subscribers #326 -> obsolete
- [ ] "berty proxy" -> connect to remote berty and expose ports on localhost #507
- [ ] Pass through DPI with an HTTP(S) Proxy #526
- [ ] Add socks proxy support #540
- [ ] Use localtunnel/ngrok/whatever to expose local API on mobile #576
- [ ] Handle peers reconnection #888
- [ ] Handle network state (wifi, 4g, no-network, etc..) #889
- [ ] Add a way to let the node know about new available providers #890
- [ ] Update networking based on (changin) context #970
- [ ] Tag peers by their channel ID (contactID/conversationID) to better cache them #1008
- [ ] improve(network): load app quickly even if started in airplane mode #1044
- [ ] send own's multiaddrs in envelopes to allow the receiver to reply back "instantly"
- [ ] switch to stream instead of unary to send messages, keep the connection open to avoid the recipient the need of performing a reverse lookup and opening a new connection
- [ ] implement rate-limiting (#173)
- [ ] discard unwanted envelopes without downloading them entirely (#219)
