### ISSUE TITLE
[META] Release / OSS

### ISSUE THREAD

**Issue by alexsland** [berty/berty#1053]
This is a **meta issue** that regroups all issues & ideas regarding the following topics :

* **Release / Going public**
* **Store release**
* **Be open-source friendly**

_Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them_

### Release
- [ ] Android: create a Digital Asset Links for deep links #713
- [ ] Remove Instabug
- [ ] Build: Android doesn't build properly for armeabi-v8a target #627
- [ ] Pre-generate 50 keypairs/userids for our future public relays + hardcode the userids in the bootstrap code #263

### Open-source friendly
- [ ] Add a CODE_OF_CONDUCT #50
- [ ] Add a CONTRIBUTING.md #51
- [ ] Create a Golang cli basic UI #134
- [ ] Generate documentation on GitHub-pages #205

### Setup I18N
- [ ] Set up a Transifex project
- [ ] Have a way to sync with it (XCode xml string, go, js etc.)
