### ISSUE TITLE
Network - Define interfaces and restructure folder /core/network

### ISSUE THREAD

**Issue by 90dy** [berty/berty#1057]
- [ ] refactor #1065 
- [ ] add /network/storage.go #1064 
- [ ] update network dynamically #1066 

- [ ] move the network from account and start network independantly #1068

- [ ] create a push transport to permit to have relay use push notification as /fcm/{fcm_id} and /apns/{apns_id}
