### ISSUE TITLE
[META] Desktop

### ISSUE THREAD

**Issue by glouvigny** [berty/berty#1101]
This is a **meta issue** that regroups all issues & ideas regarding the following topics :

* **Desktop app**
* **Slack deprecation**

_Following subjects can be linked to issues that are closed but not implemented yet, you can re-open those issues when starting to work on one of them_

### App package:
    

- [x] [p1] [2d] #1098 Bridge core with Electron front using https://github.com/asticode/go-astilectron
- [x] [p1] [2d] #1098 Makefile rules to build app
- [x] [p1] [½d] App Icon (windows, macos, linux)
- [x] [p2] Resolve linked lib issues (eg. libcrypto) to have a fully standalone app
- [x] [p2] #1143 App won't start from finder (on first launch)
- [ ] [p3] Tests desktop builds in CI
- [x] [p4] Distribute builds via YOLO
- [x] [p4] App updates via YOLO #1177 
- [x] [p4] Signed app (win32, win64, macos #1159, linux64)
- [ ] [p9] berty:// links support (windows, macos, linux)

### Core improvements:
- [x] [p1] [2d] Conversation add/remove members (see #43)
- [x] [p1] [2d] Conversation ensure events are received by all members (see #178)
- [x] [p2] [2d] Conversation topics/titles (#1127)
- [ ] [p2] [1d] Specific network configuration
- [ ] [p2] [1d] #794 Wizz
- [ ] [p3] [1+w] #14 Multi device
    - [ ] [p3] [1d] Request link from new device (eg. scan QR code with PeerID on existing)
    - [ ] [p3] [1d] Accept/refuse link from existing device (eg. check fingerprint on existing)
    - [ ] [p3] [1w] Sync database
    - [ ] [p4] Unlink device
- [ ] [p3] [2d] Store database secret (encryption key) in keychain (mobile, tablet, desktop)
- [ ] [p4] Search messages
- [ ] [p4] @mentions
- [ ] [p9] Links previews
- [ ] [p9] /giphy
- [ ] [p9] Share files
- [ ] [p9] Share images
- [ ] [p9] Pin/star messages

### UI/UX fixes:
- [x] [p1] [3d] #1110 Sidebar (tablet, desktop)
- [ ] [p1] [2d] Keyboard shortcuts (mobile, tablet, desktop)
    - [x] [p1] [1d] #1102 Send message (`Enter`)
    - [x] [p3] [1d] #1102 On boarding display name (`Enter`)
    - [x] [p2] [1d] #1116 Switch conversation (eg. Slack's `⌘+K`/`⌘+T`)
    - [x] [p2] [1d] #1117 Dismiss modals (eg. `Escape`)
    - [ ] [p4] Go to previous/next conversation (`⌥+↑`, `⌥+↓`)
- [x] [p1] [3d] #1109 Display notifications (windows, macos, linux)
- [ ] [p2] Handle scroll properly (up/down are inverted when natural scrolling is used on mac) see https://github.com/necolas/react-native-web/issues/995
- [x] [p2] [1d] #1126 Make URLs clickable (mobile, tablet, desktop) (consider https://www.npmjs.com/package/react-native-markdown-renderer)
- [ ] [p2] [1d] On boarding tweaks on desktop build
- [x] [p2] [1d] #1110 Handle window resize properly (might be fixed via #1110)
- [ ] [p9] Hide back button if topmost screen on split view (see https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/Header/Header.js#L372)
- [x] [p9] #1144 Handle resize of window to have a responsive view

### Bot:
- [ ] [p3] [1w] Webhooks support (eg. Github repo updates)
- [ ] [p9] [1w] Slack bridge

_p{1,9} indicates a priority, 1 is the most important, 9 the least important
{½,1,9}{d,w} indicates a rough time estimate_
