### ISSUE TITLE
[meta] "Berty Protocol" (initial crypto plan)

### ISSUE THREAD

**Issue by moul** [berty/berty#1182]
## Intro

**Berty Protocol** is the initial complete plan to handle every kind of communication without server.

This protocol focuses on supporting network split but lacks performance for large channels (we plan to add optional relays to help to maintain good performances for large channels)

---

We identify at least 3 different kinds of channels that may use or not the same technology:

* Group conversation of at least 2 devices, that can support adding/removing devices
* Trusted 1-1 device communication, can be used to synchronize databases (can be restricted to sync communication)
* Untrusted 1-1 device communication, to add/invite contacts, share routing, etc

---

The main concepts are:

* To avoid having shared objects that can be unsynced with potential merging issues, the idea is not to have one shared key per conversation, but one per sender per conversation, so a conversation of 10 devices is not 10 devices updating the same object, but 10 objects updated by one unique author and read by 9 other ones (easier to reconstruct unsynced object/chain)
* Devices can relay events from a peer to another (we need to save signatures at least temporarily)
* Forward secrecy is based on a counter or a hash chaining that is unique to a sender for a conversation
* The protocol allows a device to "ask" other devices some pieces of information that provides enough information to know what events were missed and what to ask 

## Todo

* [ ] Write the protocol specification
  * [x] Define which KDF to use and which data to pass to it
  * [x] Define add contact protocol (DH device by device)
  * [ ] Define add new device to a contact
  * [x] Define create conversation
  * [ ] Define add one of my device to a conversation
  * [x] Define add one of my contact devices to a conversation
  * [x] Define send event on a conversation
  * [ ] Define request history of a conversation (potentially through third-party users)
  * [x] Define send event to a trusted device (1to1)
  * [x] Define send event to an untrusted device (1to1)
  * [ ] (Optional) Define remove device from a conversation
  * [ ] (Optional) Define remove/block contact
  * [ ] (Optional) Define add new device to myself
  * [ ] (Optional) Define remove a device from myself
* [ ] PoC each sub parts
  * [ ] Keep hardware enclave for database opening and contact identity operations, but switch to NACL for high level messaging
  * [ ] Diffie-Hellmann for untrusted devices
  * [ ] Read some documentation about torrent file handling and see if we can take something
  * [ ] Write the key derivation system
  * [ ] Write a standalone library with unit tests that focus on asynchronous conversation handling with as much edge cases as possibles including invalid timestamps, very long delays etc
  * [ ] Write "Synchornization helpers" that allow a device to ask other devices for missing pieces of data
  * [ ] As soon as we have other pieces developed, write the "invite" mechanism
  * [ ] Same as above for the "/kick" mechanism
  * [ ] Develope the "device capabilities" features that allow a device to propose its "dispatching" feature to the community or to its contact devices
* [ ] Document optimizations ideas
  * [ ] Relay / Dispatcher, with MLS?
  * [ ] IPFS PubSub
  * [ ] ...

Child of #1046
