### ISSUE TITLE
Improve network reliability

### ISSUE THREAD

**Issue by gfanton** [berty/berty#1235]
The network is not reliable enough as it should be, experiment, improve & fixes until an acceptable state.

### Improvement/fixes:
- [x] Add local translate record (mDNS & BLE) #1234 
- [x] Automatically filter private ip when on cellular #1224 
- [x] Publish only public IP / p2pcircuit on DHT-CSKV (or connect only on those when sender got the receiver's peerinfo from DHT-CSKV) #1238 
- [ ]  Add a setting that allow users to communicate only via local network (BLE / private IP) if available, even if they're connected to internet

### Experiment:
- [x] [QUIC reuse port](https://github.com/libp2p/go-libp2p-quic-transport/pull/63) on cellular #1237

### Checks/tests:
- [ ] Make an inventory of the effectiveness of go-lip2p's NAT traversal methods (UPNP, STUN / Hole-Punching, etc...) in different context (4G free, SFR, etc... differents router with different NATs, etc...) 

----
_This issue is in an "in progress" state has it will certainly expend over time until we are satisfy by the network reliability_
