### ISSUE TITLE
[META] MVP roadmap

### ISSUE THREAD

**Issue by aeddi** [berty/berty#1315]
MVP roadmap v2:
---

Protocol:
-
<img width="1404" alt="Screen Shot 2019-08-01 at 1 52 18 PM" src="https://user-images.githubusercontent.com/22729528/67412658-f802c300-f5bf-11e9-8224-2e7f4ac0eaae.png">

### Issues:
- [ ] Define and implement the event system (protocol -> application) #1467
- [x] Basic go-orbit-db log with custom accesscontroller #1461 
- [x] Implement member log including accesscontroller #1463, depends on #1461
- [x] Implement setting log including accesscontroller #1464, depends on #1461
- [ ] Implement message log including accesscontroller #1465, depends on #1461
- [x] Implement secret log including accesscontroller #1466, depends on #1461
- [ ] Implement message/invitation sending and reception #1472, depends on #1467
- [ ] Implement invitation creation #1470, depends on #1472
- [ ] Implement group creation #1471, depends on  #1463, #1464, #1465, #1466, #1470
- [ ] Implement message/invitation sending and reception #1472, depends on #1467
- [ ] Implement invitation accept #1474, depends on #1471
- [ ] Implement invitation discard and group leave #1475, depends on #1474
- [ ] Implement secret exchange #1476, depends on #1471
- [ ] Implement group setting #1477, depends on #1471
- [ ] Implement account init #1478, depends on #1471 
- [ ] Implement link new device #1479, depends on #1478
- [ ] Implement contact request link creation #1480, depends on #1478
- [ ] Implement contact request link reset/cancel #1481, depends on #1480 
- [ ] Implement send/accept contact request #1484, depends on #1471, #1480, #1483
- [ ] Implement discard/block contact request and remove contact #1485, depends on #1484 
- [ ] Implement rendez-vous point system #1483, depends on #1458
- [ ] Implement pinning service #1482, depends on #1460

### Debates blocking MVP implem:
- [ ] Rendez-vous point system architecture #1458
- [ ] Pinning service architecture  #1460

---

Chat:
-

### Issues:
- *TODO*

---

UI/Front:
-
<img width="1029" alt="Screen Shot 2019-10-25 at 12 31 36 PM" src="https://user-images.githubusercontent.com/5222525/67568976-f48d4a00-f72d-11e9-807c-d7152a6b9f7a.png">

### Issues:
- *TODO*
