### ISSUE TITLE
[META] Debates and discussions

### ISSUE THREAD

**Issue by aeddi** [berty/berty#1457]
This issue is intended to list all the debates, discussions or thoughts in progress or archived. Thanks to check the corresponding box when a debate is closed.

### Protocol:
- [ ] Rendez-vous point system that allows to find a peer based on an arbitrary value (groupID, contactID, etc...): #1458 
- [ ] Pinning service, an infrastructure hosted by us or by any Berty user that allows GroupID ressources (message, attachements, etc...) to be highly available: #1460 
- [ ] Secondary app that will be used as demo / code example for the protocol: #1462
- [ ] Protocol documentation for (billions of) developers that will use it: *TODO*
- [ ] Protocol audit to ensure that we'll provide a secured SDK and messaging app: #1459 
- [ ] Anti-DDOS protections #1510 

### Chat:
- [ ] Define chat code structure and architecture, including bridges with UI and protocol: #1306

### UI / Front:
- *TODO*

### Global:
- [x] Error codes management: from protocol to chat (or any other app) and from chat to UI: #1453, #1452 
- [ ] CI and build system: #1394 
- [ ] Event sourcing on top of IPFS / OrbitDB, for the bridges between the different layers or nothing: *TODO*
- [ ] Berty IM desktop application architecture: *TODO*
- [ ] Organize external contributions #966
