### ISSUE TITLE
[META] Chat - MVP

### ISSUE THREAD

**Issue by 90dy** [berty/berty#1569]
# Beta Release
- [ ] setup yolo v2 #1570 
- [ ] setup build for staff and yolo for android #1571
- [ ] setup build for staff and yolo for ios #1572
- [ ] setup fastlane for ios #1573
- [x] setup buildkite linux agent for android #1574
- [ ] setup buildkite darwin agent for ios #1575
- [x] generate android .apk on buildkite #1576
- [ ] generate ios .ipa on buildkite #1577
- [x] release android .apk on yolo from buildkite #1578
- [ ] release ios .ipa on yolo from buildkite #1579

# UI/UX
- [x] decouple styles from stories #1548 
- [x] integrate navigation to main screens #1580
- [x] integrate navigation to settings screens #1581
- [x] integrate navigation to chat screens #1582
- [x] integrate styles to main screens #1583
- [x] integrate styles to settings screens #1584
- [x] integrate styles to chat screens #1585

# Store
- [x] create proto for defining entities and services #1562 
- [x] create template and generate basic helpers for redux-saga #1562 

# Protocol
- [x] create go-orbitdb react-native compatible pkg #1566 
- [ ] implement account log (for devices, conversations, contacts ...) #1586
- [ ] implement group log (for settings, members, messages) #1587

# Features
- [ ] account list #1588
- [ ] account create #1589
- [ ] account open #1590
- [ ] contact request send #1591
- [ ] contact request accept #1600
- [ ] contact list #1592
- [ ] conversation create #1593
- [ ] conversation list #1594
- [ ] member invite #1595
- [ ] member join #1596
- [ ] member list #1597
- [ ] request list #1598
- [ ] request accept #1599
- [ ] message send #1601
- [ ] implement message list #1602
