### ISSUE TITLE
Prepare this repo for Open-Source

### ISSUE THREAD

**Issue by moul** [berty/berty#1754]
* [x] Update README.md (#1755)
* [x] Cleanup Issues (closed issues will be using this label: [`cleanup-24-03-2020`](https://github.com/berty/berty/labels/cleanup-24-03-2020))
* [x] Try to find a solution to display an explicit error for people trying to go-get `github.com/berty/berty` or `berty.tech/berty<2.0.0`
* [x] Add dedicated README for react-native (#1814)
* [x] Add build instructions for iOS/Android (see #1766)

**Comment by moul** [comment]
Reopening this issue to keep track of people feedback about things that need to be configured for open-source

**Comment by ekelen** [comment]
If react-native and iOS+Android READMEs are separate documents, where will we put them?

**Comment by moul** [comment]
make everything you can to limit the amount of different pages

people are lazy to click, click, click, instead they are very used to use "ctrl+f"

start with one doc, even if it's very big, then we will see in another step if we really need to split it

LGTY?

**Comment by ekelen** [comment]
Agree with monoreadme. Added Chat build instructions to the react-native/storybook README (pending review) #1818

**Comment by moul** [comment]
Closing this issue, thanks for your help @ekelen :+1:
