### ISSUE TITLE
improvements on mini

### ISSUE THREAD

**Issue by glouvigny** [berty/berty#2072]
- [x]  ACK support (#2077)
- [x]  New data appended badge (#2079)
- [x]  Pastable `/contact accept` (#2078)
- [x]  `/contact accept all` (#2078)
- [x]  Show full conversation pk
- [ ] check if non-binary base64ed data should be made available in clear (not only conversation pk) 
- [x] make it easier to know the peer id
- [x] improve filterability of logger (replace `zap.Logger(msg)` by `zap.Logger("recv", zap.String("msg", msg))`)
- [x] support display names (#2088)
- [x] default behavior should be to set a datastore persistency somewhere in the homedir (#2092)

**Comment by moul** [comment]
* [ ] check if non-binary base64ed data should be made available in clear (not only conversation pk) 
* [ ] make it easier to know the peer id
* [ ] improve filterability of logger (replace `zap.Logger(msg)` by `zap.Logger("recv", zap.String("msg", msg))`)
* [ ] support display names

**Comment by moul** [comment]
* [ ] default behavior should be to set a datastore persistency somewhere in the homedir

**Comment by moul** [comment]
* [ ] sometimes, berty mini get stuck at launch
    <a href="https://www.loom.com/share/162fb680c31241688c9f44d90fbdd92c"> <p>iTerm2 - moul@fwrz: ~ - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/162fb680c31241688c9f44d90fbdd92c-with-play.gif"> </a>
    ![](https://media.discordapp.net/attachments/691689574233276416/723471208732950578/Manfreds-iMac_-_Screen_Shot_2020-06-19_at_11.36.12.png?width=1174&height=230)

**Comment by moul** [comment]
🕚 Closing as no recent updates. Please reopen if you need any updates to this ticket.
