### ISSUE TITLE
[META] Improvement ideas 💡

### ISSUE THREAD

**Issue by moul** [berty/berty#2402]
This meta issue contains various ideas that may or may not be implemented one day, it's a good place to put things that may create too much noise in the list of real issues

## Code Quality

* [ ] switch moment.js usage to day.js and remove moment.js (#2174)

## Bots

* [x] betabot, a bot dedicated to onboard people discovering the app
* [ ] testbot, a bot dedicated to unittest and integration tests that allow testing the app in real conditions (without mocks)
* [ ] devbot, a bot dedicated to berty developers (staff and external), similar to betabot, without the onboarding scenario and with more advanced debugging helpers
* [ ] bertybot go library, a library improving berty bots' development in go

**Comment by nett-ef** [comment]
I vote for the following ideas:
- clear chat history
- remove individual messages
- self-destructing message timer
- password lock

All of the above features work as in Signal by cleaning up local history from user's device. 
I've read the FAQ about BOR messages but there is an example when it's needed: a friend of mine is visiting BY or KZ where people are protesting on streets. I'm sure that he uses the official client so there's no fear of modified client. But there is a fear of friend being caught by the bad guys. Some remediation measures are needed: self-destructing message timer allows us to set 'retention policy' on chat messages reducing the amount of messages being read in the worst-case scenario when a bad guy seizes the phone. Ability to remove the chat or individual messages from the chat allows the friend to clean up history when he gets suspicious that the bad guys can arrest him. The password lock further increases the security by preventing the bad guys from accessing the messenger until the friend tells them the password. He may wait for retention period to expire before telling the password and also, most of the bad guys are not technical experts so they need time to find an expert.
Disclaimer: the above cases are purely imaginary any coincidence with the real world is just a coincidence; we discuss weather and share cute kittens ;)

**Comment by jefft0** [comment]
Will ask @gfanton if we have really implemented "support encrypted invite links (berty ID) berty://enc/..."

**Comment by jefft0** [comment]
At one point, "betabot, a bot dedicated to onboard people discovering the app" was implemented, but we removed it because Apple App Store doesn't like "beta" in the product code.

**Comment by jefft0** [comment]
@costinberty to look for the Miro board with "add a big-picture of the architecture with high-level components interaction"

**Comment by jefft0** [comment]
Ask @moul how we're using (and paying for) Datadog (or other such services).

**Comment by costinberty** [comment]
support encrypted invite links (berty ID) berty://enc/... is at least partially implemented on back-end but not front-end. Here are some tests writte for this: https://github.com/berty/berty/blob/master/go/pkg/bertylinks/links_test.go#L243 

We need to investigate a bit to see what is missing.

**Comment by jefft0** [comment]
Removed item "find a way to sync or at least backup our Datadog configuration somewhere in a git repo". We're not using the Datadog service now.

**Comment by jefft0** [comment]
Maybe make a separate issue to investigate the status of encrypted links, so that we can backlog this meta issue.

**Comment by costinberty** [comment]
Opened https://github.com/berty/berty/pull/4820 to add the Berty Messenger High Level Architecture to the repo

**Comment by jefft0** [comment]
> Opened #4820 to add the Berty Messenger High Level Architecture to the repo

The PR is merged. Marked "add a big-picture of the architecture with high-level components interaction" as done.

**Comment by jefft0** [comment]
All the items in the description have been reviewed. We addressed some of them, and we split off issues like #4822. Put this in backlog and revisit occasionally when we have resources.
