### ISSUE TITLE
[CI] Add integration tests in the CI pipeline

### ISSUE THREAD

**Issue by aeddi** [berty/berty#939]
- [x] Implement basic integration tests on react-native / react-native-web using [Cavy](https://github.com/pixielabs/cavy)  (#701)
- [x] Get ouput from JS console on terminal (to get Cavy result) (#935)
- [ ] Implement an agent that pull PR and launch integration tests on RN mobile debug / release (physical devices) and RN web (#937)
- [ ] Bind Cavy hooks -> custom library components in a clean way (#960)
